### ISSUE TITLE
Check this task

### ISSUE THREAD

**Issue by rudnitskih** [scandy5/css#1]
Highlight elements with data-href that contains in the set highlight_me word, only like a separate word – text-decoration: underline

https://github.com/scandy5/css/blob/master/style/style-part2.css#L27

**Comment by scandy5** [comment]
> Highlight elements with data-href that contains in the set highlight_me word, only like a separate word – text-decoration: underline
> 
> https://github.com/scandy5/css/blob/master/style/style-part2.css#L27

не понял этого комментария, так, как я понял, то нужно выделить элементы с data-href, которые содержат в себе heighlight_me, подчеркнув, обьясни пожалуйста, чего я не сделал

**Comment by rudnitskih** [comment]
Задание звучит как `set highlight_me word, only like a separate word`. Тоесть element c data-href="almost_linkhighlight_me" подсвечивать не нужно
