### ISSUE TITLE
Highlight labels when user set checked to checkboxes

### ISSUE THREAD

**Issue by rudnitskih** [scandy5/css#3]
Check implementation of this task

**Comment by scandy5** [comment]
Я не понял задания, нужно, чтобы лейблы подчеркивались? Они не связаны с чекбоксами

**Comment by scandy5** [comment]
> Check implementation of this task
Я не понял задания, нужно, чтобы лейблы подчеркивались? Они не связаны с чекбоксами

**Comment by rudnitskih** [comment]
да нужно чтобы подчерквивались лейбл который стоит после checked checkbox

**Comment by scandy5** [comment]
> да нужно чтобы подчерквивались лейбл который стоит после checked checkbox

это в html ничего менять не нужно? чекбокс и лейбл же никак не связаны

**Comment by rudnitskih** [comment]
не связаны, но все равно можно подчеркнуть label если использовать `:checked` и `+`
